version: '3.10'
services:
  web:
    build: .
    container_name: web
    command: python /project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
volumes:
  postgres_data: